M48
; DRILL file {KiCad 9.0.7} date 2026-07-05T06:35:04-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-05T06:35:04-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X37.375Y-85.575
X37.375Y-89.975
X37.4Y-99.375
X37.4Y-103.775
T2
X41.88Y-112.405
X41.88Y-125.105
M30
